FROM maven:3.9.6-eclipse-temurin-21

# Installer Chrome et les dépendances nécessaires pour le mode headless
RUN apt-get update && apt-get install -y \
    google-chrome-stable \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*