name: CI for Backend Service

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-backend-image:latest .

      - name: Run tests with Docker
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_JSON }}
        run: |
          docker run \
          --rm \
          -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
          -e FIREBASE_CONFIG_JSON="${{ secrets.FIREBASE_CONFIG_JSON }}" \
          my-backend-image:latest sh -c "mvn test"