name: CI for Backend Service

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 1 : Lancer les tests avec Maven dans un conteneur
      - name: Run tests with Maven
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_JSON }}
          SPRING_MAIL_HOST: ${{ secrets.SPRING_MAIL_HOST }}
          SPRING_MAIL_PORT: ${{ secrets.SPRING_MAIL_PORT }}
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
        run: |
          docker run --rm \
            -v $PWD:/app \
            -w /app \
            -e JWT_SECRET_KEY="$JWT_SECRET_KEY" \
            -e FIREBASE_CONFIG_JSON="$FIREBASE_CONFIG_JSON" \
            -e SPRING_MAIL_HOST="$SPRING_MAIL_HOST" \
            -e SPRING_MAIL_PORT="$SPRING_MAIL_PORT" \
            -e SPRING_MAIL_USERNAME="$SPRING_MAIL_USERNAME" \
            -e SPRING_MAIL_PASSWORD="$SPRING_MAIL_PASSWORD" \
            maven:3.9.6-eclipse-temurin-21 \
            mvn clean test

      # Étape 2 : Si les tests passent, build de l'image finale
      - name: Build Docker image for deployment
        run: docker build -t my-backend-image:latest .
