name: CI for Backend Service

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test with Docker
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          docker build -t my-backend-image:latest .
          docker run --rm -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} my-backend-image:latest sh -c "mvn test"